version: '2.1'

services:
  test:
    working_dir: /drewmendenhall.com
    env_file: .env
    image: cypress/included:12.3.0@sha256:86e3bff9634b85a5239a65974ac3c98f51277a8e1519fbd57b5e528f55ab8bf7
    volumes:
      - .:/drewmendenhall.com
