name: typescript

on:
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - .github/actions/setup-node/
      - .github/workflows/typescript.yml
      - package.json
      - tsconfig.json
      - yarn.lock
  push:
    branches:
      - main

jobs:
  typescript:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: ./.github/actions/setup-node
      - run: yarn tsc
