name: yarn

on:
  push:
    paths:
      - .github/actions/setup-node/
      - .github/workflows/yarn.yml
      - yarn.lock

concurrency: yarn

jobs:
  yarn:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: ./.github/actions/setup-node
